import { UnitTemplate } from "./types";

export const SwordsmanTemplate: UnitTemplate = {
  cls: "Swordsman",
  maxHP: 700,
  maxMP: 10,
  ATK: 110,
  DEF: 130,
  MATK: 40,
  MDEF: 40,
  ACC: 110,
  EVA: 60,
  CR: 0.1,
  SPD: 12,
  MOV: 2,
  BLK: 0.25,
  passive: { name: "健體強身", baseMul: { DEF: 1.3 } },
  skills: [
    {
      id: "basic",
      name: "普通攻擊",
      type: "Physical",
      multiplier: 0,
      mpCost: 0,
      rangeFront: 1,
      isBasic: true,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "skill1",
      name: "奮力一擊",
      type: "Physical",
      multiplier: 0.5,
      mpCost: 6,
      rangeFront: 1,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
  ],
  finalDR: { physical: 1, magical: 1 },
};

export const MageTemplate: UnitTemplate = {
  cls: "Mage",
  maxHP: 450,
  maxMP: 26,
  ATK: 40,
  DEF: 40,
  MATK: 680,
  MDEF: 600,
  ACC: 110,
  EVA: 70,
  CR: 0.05,
  SPD: 10,
  MOV: 3,
  BLK: 0,
  passive: { name: "魔力回復", baseAdd: { mpRegen: 1.5 * 3 - 3 } },
  skills: [
    {
      id: "basic",
      name: "普通攻擊",
      type: "Physical",
      multiplier: 0,
      mpCost: 0,
      rangeFront: 1,
      isBasic: true,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "skill1",
      name: "火球術",
      type: "Magical",
      multiplier: 0.75,
      mpCost: 10,
      rangeFront: 4,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "skill2",
      name: "火球術．大",
      type: "Magical",
      multiplier: 0.5,
      mpCost: 20,
      rangeFront: 0,
      area: { kind: "Rect", rectW: 3, rectD: 2 },
      targetGroup: "group",
      targetTeam: "enemy",
    },
  ],
  finalDR: { physical: 1, magical: 1 },
};

export const ArcherTemplate: UnitTemplate = {
  cls: "Archer",
  maxHP: 500,
  maxMP: 16,
  ATK: 110,
  DEF: 60,
  MATK: 40,
  MDEF: 160,
  ACC: 130,
  EVA: 85,
  CR: 0.3,
  SPD: 14,
  MOV: 3,
  BLK: 0,
  passive: { name: "百步穿楊", baseAdd: { CR: 0.05 } },
  skills: [
    {
      id: "basic",
      name: "普通攻擊",
      type: "Physical",
      multiplier: 0,
      mpCost: 0,
      rangeFront: 3,
      isBasic: true,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "skill1",
      name: "必殺狙擊",
      type: "Physical",
      multiplier: 1.0,
      mpCost: 8,
      rangeFront: 5,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
  ],
  finalDR: { physical: 1, magical: 1 },
};

export const RogueTemplate: UnitTemplate = {
  cls: "Rogue",
  maxHP: 600,
  maxMP: 14,
  ATK: 140,
  DEF: 60,
  MATK: 40,
  MDEF: 160,
  ACC: 125,
  EVA: 110,
  CR: 0.2,
  SPD: 16,
  MOV: 4,
  BLK: 0.05,
  passive: { name: "盜賊奧義", baseAdd: { EVA: 20 } },
  skills: [
    {
      id: "basic",
      name: "普通攻擊",
      type: "Physical",
      multiplier: 0,
      mpCost: 0,
      rangeFront: 1,
      isBasic: true,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "skill1",
      name: "背刺",
      type: "Physical",
      multiplier: 1.0,
      mpCost: 6,
      rangeFront: 1,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
  ],
  finalDR: { physical: 1, magical: 1 },
};

export const AdminTemplate: UnitTemplate = {
  cls: "ADMIN",
  maxHP: 900,
  maxMP: 30,
  ATK: 140,
  DEF: 110,
  MATK: 180,
  MDEF: 160,
  ACC: 140,
  EVA: 110,
  CR: 0.15,
  SPD: 18,
  MOV: 10,
  BLK: 0.2,
  passive: {
    name: "系統管理員",
    baseAdd: {
      ATK: 20,
      DEF: 20,
      MATK: 40,
      MDEF: 40,
      ACC: 10,
      EVA: 10,
      SPD: 2,
      MOV: 1,
      CR: 0.05,
      mpRegen: 2,
      BLK: 0.05,
    },
    baseMul: { ATK: 1.1, DEF: 1.1, MATK: 1.1, MDEF: 1.1 },
    postDR: { physical: 0.9, magical: 0.85 },
  },
  skills: [
    {
      id: "basic",
      name: "系統平A",
      type: "Physical",
      multiplier: 0,
      mpCost: 0,
      rangeFront: 1,
      isBasic: true,
      area: { kind: "Line" },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "adm_line",
      name: "管理光束",
      type: "Magical",
      multiplier: 0.8,
      mpCost: 8,
      rangeFront: 4,
      area: { kind: "Line" },
      targetGroup: "group",
      targetTeam: "enemy",
    },
    {
      id: "adm_rect",
      name: "制裁領域",
      type: "Magical",
      multiplier: 1.0,
      mpCost: 15,
      rangeFront: 3,
      area: { kind: "Rect", rectW: 3, rectD: 2 },
      targetGroup: "single",
      targetTeam: "enemy",
    },
    {
      id: "adm_heal",
      name: "系統修復",
      type: "Magical",
      multiplier: 0,
      mpCost: 10,
      rangeFront: 3,
      area: { kind: "SelfArea" },
      targetGroup: "group",
      targetTeam: "ally",
      effects: { healHP: 120, restoreMP: 8 },
    },
    {
      id: "adm_buff",
      name: "超頻模式",
      type: "Physical",
      multiplier: 0,
      mpCost: 8,
      rangeFront: 5,
      area: { kind: "SelfArea" },
      targetGroup: "single",
      targetTeam: "ally",
      effects: {
        applyBuff: {
          to: "unit",
          buff: {
            name: "超頻",
            turns: 2,
            add: { ATK: 30, SPD: 2, MOV: 1, ACC: 10, CR: 0.05 },
            mul: { ATK: 1.15, DEF: 1.1 },
            postDMG: 1.15,
          },
        },
      },
    },
    {
      id: "adm_debuff",
      name: "權限限制",
      type: "Physical",
      multiplier: 0,
      mpCost: 10,
      rangeFront: 3,
      area: { kind: "Rect", rectW: 3, rectD: 2 },
      targetGroup: "group",
      targetTeam: "enemy",
      effects: {
        applyBuff: {
          to: "area",
          buff: {
            name: "被限制",
            turns: 2,
            add: { ACC: -20, EVA: -20, SPD: -2 },
            mul: { ATK: 0.85, MATK: 0.85, DEF: 0.9, MDEF: 0.9 },
          },
        },
      },
    },
  ],
  finalDR: { physical: 1, magical: 1 },
};

export const Templates = {
  Swordsman: SwordsmanTemplate,
  Mage: MageTemplate,
  Archer: ArcherTemplate,
  Rogue: RogueTemplate,
  ADMIN: AdminTemplate,
} as const;

export const CLASS_LIST = Object.keys(Templates) as ClassKey[];
export const RANDOM_CLASS_LIST = CLASS_LIST.filter((k) => k !== "ADMIN"); // 隨機角色移除 ADMIN

export type ClassKey = keyof typeof Templates;

export const SHORT: Record<ClassKey, string> = {
  Swordsman: "Swd",
  Mage: "Mag",
  Archer: "Arc",
  Rogue: "Rog",
  ADMIN: "Adm",
};
